### ISSUE TITLE
Do you have the raw text for each class?

### ISSUE THREAD

**Issue by fallcat** [tzuf/ZEST#1]
Hello!

I'm wondering if you have the raw text for each class that contains wikipedia and all about birds articles? I hope to use other models to extract features. Although I have my own scraped text, it might be different and I hope to be able to compare with previous works. It would be great if you could share the raw text. Thank you!

**Comment by tzuf** [comment]
Hi Weiqiu,

The raw Wikipedia text is here
<https://drive.google.com/file/d/0B_8vkk7CF-pwckxLQTVkcDBadGc/view>.
Good luck!

**Comment by fallcat** [comment]
Thank you so much! Is CUBird_WikiArticles what you used to compute TF-IDF? Seems that CUBird_Sentences and CUBird_WikiArticles are the same?

**Comment by tzuf** [comment]
There is very little difference. If I remember correctly I used the CUB
articles

**Comment by fallcat** [comment]
OK! Thanks a lot!
